on:
  pull_request:
    branches:
      - main

env:
  CACHE_VERSION: v1

name: SimDB checks
jobs:
  clang-format:
    name: Ensure clang-format was run
    runs-on: ubuntu-24.04

    steps:
      - name: Clone SimDB
        uses: actions/checkout@v4

      - name: Install clang-format
        run: |
          sudo apt-get update --fix-missing
          sudo apt-get install -y clang-format-19

      - name: Check formatting
        run: |
          ./.github/actions/clang-format-check.sh

  check-headers:
    name: Self-contained header check (${{ matrix.BUILD_TYPE }}-${{matrix.COMPILER}})
    runs-on: ubuntu-24.04

    strategy:
      matrix:
        compiler: [gcc, clang]
        build_type: [Debug, Release]

    steps:
      - name: Clone SimDB
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          sudo apt-get update --fix-missing
          sudo apt-get install -y libboost-all-dev

      - name: Run self-contained header check
        run: python3 scripts/check-headers.py

  build_test_job:
    strategy:
      matrix:
        os: [ubuntu-24.04]
        BUILD_TYPE: [Debug,Release]
        COMPILER: [gcc,clang]

    name: Regress SimDB on Ubuntu (${{ matrix.BUILD_TYPE }}-${{matrix.COMPILER}})
    runs-on: ${{ matrix.os }}

    # Set up a global environment variable for build scripts
    env:
      SIMDB_BUILD_TYPE: ${{ matrix.BUILD_TYPE }}
      COMPILER:         ${{ matrix.COMPILER }}

    steps:
      - name: Setup Git Identity
        run: |
          git config --global user.email "runner@github.com"
          git config --global user.name "Github Runner"

      # Get SimDB
      - name: Clone SimDB
        uses: actions/checkout@v4

      # Install missing packages to make everything build
      - name: Install packages needed for SimDB
        run: |
          sudo apt-get update --fix-missing
          sudo apt-get install -y libboost-all-dev llvm lld sqlite3 libsqlite3-dev

      # Invoke CMake
      - name: CMake
        run: ./.github/actions/cmake.sh

      # Regress
      - name: Regress
        run: ./.github/actions/regress.sh

      # Save error logs, etc
      - name: Save artifacts
        if: failure()
        uses: actions/upload-artifact@main
        with:
          name: ErrorLogs-${{matrix.BUILD_TYPE}}-${{matrix.COMPILER}}
          path: ${{matrix.BUILD_TYPE}}/

  build_test_job_macos:
    strategy:
      matrix:
        os: [macos-15]
        BUILD_TYPE: [Debug,Release]
        COMPILER: [clang]

    name: Regress SimDB on MacOS (${{ matrix.BUILD_TYPE }}-${{matrix.COMPILER}})
    runs-on: ${{ matrix.os }}

    # Set up a global environment variable for build scripts
    env:
      SIMDB_BUILD_TYPE: ${{ matrix.BUILD_TYPE }}
      COMPILER:         ${{ matrix.COMPILER }}
      CCACHE_DIR:       /Users/runner/.ccache

    steps:
      - name: Setup Git Identity
        run: |
          git config --global user.email "runner@github.com"
          git config --global user.name "Github Runner"

      # Get SimDB
      - name: Clone SimDB
        uses: actions/checkout@v4

      # Install missing packages to make everything build
      - name: Install packages needed for SimDB
        run: |
          brew update
          brew install boost sqlite3 zlib

      # Setup CCache to cache builds
      - name: ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: ${{ matrix.os }}-${{ matrix.BUILD_TYPE }}-${{ matrix.COMPILER }}-ccache-${{ github.ref_name }}
          restore-keys: |
            ${{ matrix.os }}-${{ matrix.BUILD_TYPE }}-${{ matrix.COMPILER }}-ccache-main
            ${{ matrix.os }}-${{ matrix.BUILD_TYPE }}-${{ matrix.COMPILER }}-ccache

      # Setup fix CCache directory permissions
      - name: ccache macOS permission fix
        run: ./.github/actions/macos_perms.sh

      # Invoke CMake
      - name: CMake
        run: ./.github/actions/cmake.sh

      # Regress
      - name: Regress
        run: ./.github/actions/regress.sh

      # Save error logs, etc
      - name: Save artifacts
        if: failure()
        uses: actions/upload-artifact@main
        with:
          name: ErrorLogs-macos-${{matrix.BUILD_TYPE}}-${{matrix.COMPILER}}
          path: ${{matrix.BUILD_TYPE}}/
